<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Query\Expr;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Query\Parameter;
/**
 * ActiviteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActiviteRepository extends \Doctrine\ORM\EntityRepository
{
	/**
	 * test doublon
	 * @return boolean faux si pas de doublon
	 * @param Activite $activite
	 */
	public function existeDeja(Activite $activite){
		$activite->getJour();
		$activite->getLibelle();
		$activite->getNbPlaces();
		$activite->getNiveau();
		$activite->getId();
		$qb = $this->createQueryBuilder('a');
		$qb	->where('a.jour = :jour')
			->andWhere('a.libelle = :libelle')
			->andWhere('a.nbplaces = :nbplaces')
			->andWhere('a.niveau = :niveau')
			->andWhere('a.id != :id')			
		;
		$qb->setParameters(new ArrayCollection(
			array( 	new Parameter('jour', $activite->getJour()), 
					new Parameter('libelle', $activite->getLibelle()), 
					new Parameter('nbplaces', $activite->getNbPlaces()), 
					new Parameter('niveau', $activite->getNiveau()), 
					new Parameter('id', $activite->getId()), 				
			))
		);
		$result = $qb->getQuery()->getOneOrNullResult();
		return null !== $result;		
	}
	
}
